spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: Lacasadibarbie88
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: spring-authentication
token:
  signing:
    #This key is used as base to generate tokens for authentication
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
